version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      root-gradle:
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: /minecraft/fabric-1.21.1
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      fabric:
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: /minecraft/forge-1.20.1
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      forge:
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: /minecraft/neoforge-1.21.1
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      neoforge:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /terminal/web-ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      web-terminal:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
