package com.mccompanion.terminal;
import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.*;import com.mccompanion.terminal.runtime.*;import java.io.*;import java.net.*;import java.net.http.*;import java.nio.file.*;import java.time.*;
final class ProviderConfigurationService{
 static final ObjectMapper JSON=new ObjectMapper();Path file(RuntimeProfile p){return p.profileDirectory().resolve("provider.json");}
 void configure(RuntimeProfile p,String baseUrl,String model,String env)throws IOException{Files.createDirectories(p.profileDirectory());ObjectNode n=JSON.createObjectNode().put("mode","openai-compatible").put("baseUrl",baseUrl).put("model",model).put("apiKeyEnv",env);JSON.writerWithDefaultPrettyPrinter().writeValue(file(p).toFile(),n);}
 void disable(RuntimeProfile p)throws IOException{Files.createDirectories(p.profileDirectory());JSON.writerWithDefaultPrettyPrinter().writeValue(file(p).toFile(),JSON.createObjectNode().put("mode","rules"));}
 JsonNode status(RuntimeProfile p)throws IOException{return Files.isRegularFile(file(p))?JSON.readTree(file(p).toFile()):JSON.createObjectNode().put("mode","rules");}
 TestResult test(RuntimeProfile p)throws Exception{JsonNode n=status(p);if(n.path("mode").asText("rules").equals("rules"))return new TestResult(true,0,"rules","No API key required");String env=n.path("apiKeyEnv").asText("MC_COMPANION_API_KEY");String key=System.getenv(env);if(key==null||key.isBlank())return new TestResult(false,0,n.path("model").asText(),"API key environment variable is not set");String base=n.path("baseUrl").asText();URI uri=URI.create(base.endsWith("/")?base+"chat/completions":base+"/chat/completions");ObjectNode body=JSON.createObjectNode().put("model",n.path("model").asText()).put("max_tokens",1);body.putArray("messages").addObject().put("role","user").put("content","ping");long start=System.nanoTime();HttpResponse<String> response=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build().send(HttpRequest.newBuilder(uri).timeout(Duration.ofSeconds(15)).header("Authorization","Bearer "+key).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(JSON.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());long ms=(System.nanoTime()-start)/1_000_000;return new TestResult(response.statusCode()/100==2,ms,n.path("model").asText(),"HTTP "+response.statusCode());}
 record TestResult(boolean success,long latencyMillis,String model,String message){}
}
