package com.mccompanion.runtime.conversation;

public enum FailureCategory {
    ALTERNATIVE_STRATEGY_AVAILABLE,
    PREREQUISITE_MISSING,
    RESOURCE_SHORTAGE,
    USER_CHOICE_REQUIRED,
    AUTHORIZATION_REQUIRED,
    INFORMATION_MISSING,
    UNSUPPORTED_CAPABILITY,
    SAFETY_BLOCKED,
    EXTERNAL_SERVICE_UNAVAILABLE,
    NO_PROGRESS
}
