package com.mccompanion.core.body.daily;

/** Durable phase names; adapters never decide phase transitions. */
public enum DailyActionPhase {
    VALIDATE,
    FIND_BED, NAVIGATE_BED, SLEEP, WAKE,
    NAVIGATE_BUCKET, FILL_BUCKET, EMPTY_BUCKET,
    APPROACH_VEHICLE, BOARD_VEHICLE, TRAVEL_VEHICLE, DISEMBARK_VEHICLE,
    EQUIP_ROD, NAVIGATE_FISH, CAST_LINE, WAIT_BITE, REEL_LINE, VERIFY_LOOT,
    SCAN_CROP, NAVIGATE_CROP, HARVEST_CROP, PICKUP_CROP, REPLANT_CROP, VERIFY_CROP,
    APPROACH_FIRST_ANIMAL, FEED_FIRST, APPROACH_SECOND_ANIMAL, FEED_SECOND, WAIT_BABY, VERIFY_BREED,
    APPROACH_TRADE, OPEN_TRADE, SELECT_TRADE, EXECUTE_TRADE, VERIFY_TRADE,
    NAVIGATE_ENCHANT, OPEN_ENCHANT, SELECT_ENCHANT, APPLY_ENCHANT, VERIFY_ENCHANT,
    NAVIGATE_BREW, OPEN_BREW, LOAD_BREW, WAIT_BREW, TAKE_BREW, VERIFY_BREW,
    EQUIP_ELYTRA, START_GLIDE, GLIDE, LAND,
    COMPLETE
}
